#! /bin/sh

bspc config border_width        1
bspc config window_gap         12
bspc config top_padding        32

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6

bspc rule -a Gimp follow=on floating=on
bspc rule -a Firefox follow=on desktop=^1
bspc rule -a vlc follow=on desktop=^5

bar &
