#! /bin/sh

bspc config border_width        1
bspc config window_gap         12
bspc config top_padding        32

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#000000"
bspc config focused_border_color "#cccccc"
bspc config presel_border_color "#555555"

bspc monitor -d browser code files media download misc

bspc rule -a Gimp desktop=misc follow=on floating=on
bspc rule -a Firefox follow=on desktop=browser
bspc rule -a vlc follow=on desktop=media 
bspc rule -a wesnoth follow=on desktop=misc fullscreen=on
bspc rule -a libreoffice follow=on desktop=misc fullscreen=on

bar &
