#!/bin/bash

# Requires lemonbar-xft-git from AUR

CURRENT_USER=$(whoami)

FONT_1="Ubuntu:style=Regular::size=10"
FONT_2="Ubuntu:style=Bold:size=10"
FONT_3="FontAwesome:style=Regular:size=8"
FONT_4="FontAwesome:style=Regular:size=9"
FONT_5="FontAwesome:style=Regular:size=10" 

BG="#00151515"
FG="#CCFFFFFF"

INACTIVE="#22FFFFFF"

BLUE="#726cc6"
RED="#c6726c"
YELLOW="#c0c66c"
GREEN="#b5e3b8"
DARKGREY="#FF555555"
PURPLE="#e3b5e0"

Active() {
    xtitle | head -c 100
}

TimeDate() { 
    echo "$(date +"%A %B %d")   %{T2}$(date +"%H:%M")%{T}"
}

Battery() {
    BATTERY_PERCENTAGE=$(acpi --battery | cut -d" " -f 4 | sed 's/[^0-9]*//g')
    BATTERY_STATUS=$( acpi --battery | tail -n 1 | cut -d" " -f 3 | sed 's/,$//' )
    BATTERY_ICON=""
    BAT_COL="$FG"

    case $BATTERY_STATUS in
           'Charging') BATTERY_ICON="" ;;
           'Full') BATTERY_ICON="" ;;
    esac
    
    if [ $BATTERY_PERCENTAGE -lt 11 ] && [ $BATTERY_STATUS == 'Discharging' ]; then BAT_COL="$RED"; fi

    echo "%{F$BAT_COL}%{T4}$BATTERY_ICON%{T}%{F-} $BATTERY_PERCENTAGE%"
}

Volume() {
    AUDIO_VOLUME=$(awk -F"[][]" '/dB/ { print $2  }' <(amixer sget Master))
    AUDIO_STATUS=$(amixer get Master | tail -n 1 | cut -d" " -f 8 | tr -d '[]')
    VOL_COL="$FG"
    VOL_ICON=""
    if [ $AUDIO_STATUS == "off" ]; then AUDIO_VOLUME=""; VOL_ICON=""; fi
    echo "%{A:amixer set Master toggle:}%{A4:amixer set Master 1db+:}%{A5:amixer set Master 1db-:}%{F$VOL_COL}%{T5}$VOL_ICON%{T}%{F-} $AUDIO_VOLUME%{A}%{A}%{A}"
}

WiFi() {
    WIFI_SSID=$(iwgetid -r)
    WIFI_COL="$FG"
    if [ -z $WIFI_SSID ]; then WIFI_COL="$INACTIVE"; fi
    echo "%{A:urxvt -e sudo wifi-menu:}%{F$WIFI_COL}%{T5}%{T}%{F-}%{A}"
}

Desktops() {
    DESKTOP_STATUS=$(bspc control --get-status | tr ":" "\n" | sed '1d' | head --lines=-1)
    DESKTOP_INFO=""
    for desktop in $DESKTOP_STATUS; do
        DESKTOP_NAME=$(echo "$desktop" | cut -c2-)
        case $desktop in
            O*|F*) DESKTOP_COLOUR="$BLUE" ;;
            o*) DESKTOP_COLOUR="-" ;;
            f*) DESKTOP_COLOUR="$DARKGREY";;
        esac
        case $DESKTOP_NAME in
            1) DESKTOP_ICON="" ;; #Browser 
            2) DESKTOP_ICON="" ;; #Coding 
            3) DESKTOP_ICON="" ;; #Files
            4) DESKTOP_ICON="" ;; #Media 
            5) DESKTOP_ICON="" ;; #Downloading 
            *) DESKTOP_ICON="" ;; #Misc
        esac
        DESKTOP_INFO="$DESKTOP_INFO  %{A:bspc desktop -f $DESKTOP_NAME:}%{F$DESKTOP_COLOUR}%{T5}$DESKTOP_ICON%{T}%{F-}%{A}"
    done

    echo "$DESKTOP_INFO"
}

Updates() {
    UP_COUNT=$(cat ~/.update_count | cut -d ";" -f 2)
    UP_ICON=""
    if [ ! $UP_COUNT == 0 ]; then echo "%{A:urxvt -e pacaur -Syu:}%{F$FG}%{T4}$UP_ICON%{T}%{F-}%{A}"; fi
}

Torrents() {
    TORRENTS=$(cat /home/$CURRENT_USER/.torrentind)
    TORRENT_COLOR="$INACTIVE"
    ACTIVE_TORRENTS=$(echo "$TORRENTS" | cut -d':' -f 1)
    COMPLETED_TORRENTS=$(echo "$TORRENTS" | cut -d':' -f 2)
    if [ $ACTIVE_TORRENTS -gt 0 ]; then TORRENT_COLOR="$FG"; fi
    if [ $COMPLETED_TORRENTS -gt 0 ]; then TORRENT_COLOR="$GREEN" ; fi

    if [ $ACTIVE_TORRENTS -gt 0 ]; then echo "%{A:urxvt -e transmission-remote-cli:}%{F$TORRENT_COLOR}%{T5}%{T}%{F-}%{A}"; fi
}

Dropbox() {
    DROPBOX_STATUS=$(dropbox-cli status | wc -l)
    if [ $DROPBOX_STATUS -gt 1 ]; then echo "%{F$FG}%{T5}%{T}%{F-}"; fi
}

CapsLock() {
    CAPS_SATUS=$(xset -q | grep 'Caps Lock:' | cut -d ' ' -f 10)
    if [ $CAPS_SATUS == 'on' ]; then echo "%{T5}%{T}"; fi
}

while true
do
    echo -e "%{l} $(Desktops) \
             %{c}$(Active) \
             %{r}$(CapsLock) $(Dropbox) $(Torrents) $(Updates) $(WiFi)  $(Volume)  $(Battery)      $(TimeDate)  "
    sleep .25
done | lemonbar -p -g 1343x23+12+12 -B $BG -F $FG -f $FONT_1 -f $FONT_2 -f $FONT_3 -f $FONT_4 -f $FONT_5 | sh
