#!/bin/bash

# Requires lemonbar-xft-git from AUR

CURRENT_USER=$(whoami)

BG="#00151515"
FG="#CCFFFFFF"

INACTIVE="#22FFFFFF"

BLUE="#726cc6"
RED="#c6726c"
YELLOW="#c0c66c"
GREEN="#b5e3b8"
DARKGREY="#FF555555"
PURPLE="#e3b5e0"

Active() {
    xtitle | head -c 80
}

TimeDate() { 
    echo "$(date +"%A %B %d")   %{T3}$(date +"%H:%M")%{T}"
}

Battery() {
    BATTERY_PERCENTAGE=$(acpi --battery | cut -d" " -f 4 | sed 's/[^0-9]*//g')
    BATTERY_STATUS=$( acpi --battery | tail -n 1 | cut -d" " -f 3 | sed 's/,$//' )
    BATTERY_ICON=""

    case $BATTERY_STATUS in
           'Charging') BAT_COL="$BLUE"; BATTERY_ICON="" ;;
           'Discharging') BAT_COL="$YELLOW" ;;
           'Full') BAT_COL="$GREEN"; BATTERY_ICON="" ;;
           *) BAT_COL="-" ;;
    esac
    
    if [ $BATTERY_PERCENTAGE -lt 11 ] && [ $BATTERY_STATUS == 'Discharging' ]; then BAT_COL="$RED"; fi

    echo "%{F$BAT_COL}%{T4}$BATTERY_ICON%{T}%{F-} $BATTERY_PERCENTAGE%"
}

Volume() {
    AUDIO_VOLUME=$(awk -F"[][]" '/dB/ { print $2  }' <(amixer sget Master))
    AUDIO_STATUS=$(amixer get Master | tail -n 1 | cut -d" " -f 8 | tr -d '[]')
    VOL_COL="$PURPLE"
    VOL_ICON=""
    if [ $AUDIO_STATUS == "off" ]; then VOL_COL="$INACTIVE"; AUDIO_VOLUME=""; VOL_ICON=""; fi
    echo "%{F$VOL_COL}%{T2}$VOL_ICON%{T}%{F-} $AUDIO_VOLUME"
}

WiFi() {
    WIFI_SSID=$(iwgetid -r)
    WIFI_COL="$GREEN"
    if [ -z $WIFI_SSID ]; then WIFI_COL="$INACTIVE"; fi
    echo "%{F$WIFI_COL}%{T2}%{T}%{F-}"
}

Windows() {
    WIN_STATUS=$(bspc control --get-status | tr ":" "\n" | sed '1d' | sed '5d')
    WIN_INFO=""
    WIN_OCC=""
    WIN_FREE=""
    for window in $WIN_STATUS; do
        case $window in
            O*|F*) WIN_ICON="$WIN_OCC"; WIN_COLOUR="-";;
            o*) WIN_ICON="$WIN_FREE"; WIN_COLOUR="-" ;;
            f*) WIN_ICON="$WIN_FREE"; WIN_COLOUR="$DARKGREY";;
        esac
        WIN_INFO="$WIN_INFO %{F$WIN_COLOUR}%{T4}$WIN_ICON%{T}%{F-}"
    done

    echo "$WIN_INFO"
}

Updates() {
    UP_COUNT=$(cat ~/.update_count | cut -d ";" -f 2)
    UP_ICON=""
    if [ ! $UP_COUNT == 0 ]; then echo "%{F$FG}%{T4}$UP_ICON%{T}%{F-}"; fi
}

Torrents() {
    TORRENTS=$(cat /home/$CURRENT_USER/.torrentind)
    TORRENT_COLOR="$INACTIVE"
    ACTIVE_TORRENTS=$(echo "$TORRENTS" | cut -d':' -f 1)
    COMPLETED_TORRENTS=$(echo "$TORRENTS" | cut -d':' -f 2)
    if [ $ACTIVE_TORRENTS -gt 0 ]; then TORRENT_COLOR="$DARKGREY"; fi
    if [ $COMPLETED_TORRENTS -gt 0 ]; then TORRENT_COLOR="$GREEN" ; fi

    if [ $ACTIVE_TORRENTS -gt 0 ]; then echo "%{F$TORRENT_COLOR}%{F-} ($COMPLETED_TORRENTS/$ACTIVE_TORRENTS)"; fi
}

Dropbox() {
    DROPBOX_STATUS=$(dropbox-cli status | wc -l)
    if [ $DROPBOX_STATUS -gt 1 ]; then echo "%{F$BLUE}%{F-}"; fi
}

while true
do
    echo -e "%{l} $(Windows) %{c}$(Active) %{r}$(Dropbox) $(Torrents) $(Updates) $(WiFi)   $(Volume)  $(Battery)      $(TimeDate)  "
    sleep .25
done | lemonbar -p -g 1343x23+12+12 -B $BG -F $FG -f "Ubuntu:style=Regular::size=10" -f "FontAwesome:style=Regular:size=11" -f "Ubuntu:style=Bold:size=10" -f "FontAwesome:style=Regular:size=9"
