#!/bin/bash

# Requires lemonbar-xft-git from AUR

CURRENT_USER=$(whoami)

FONT_1="Ubuntu:style=Regular::size=10"
FONT_2="Ubuntu:style=Bold:size=10"
FONT_3="FontAwesome:style=Regular:size=8"
FONT_4="FontAwesome:style=Regular:size=9"
FONT_5="FontAwesome:style=Regular:size=10" 

source bar-colors.sh

TimeDate() { 
    echo "$(date +"%A %B %d")    %{T2}$(date +"%H:%M")%{T}"
}

Battery() {
    BATTERY_PERCENTAGE=$(acpi --battery | cut -d" " -f 4 | sed 's/[^0-9]*//g')
    BATTERY_STATUS=$( acpi --battery | tail -n 1 | cut -d" " -f 3 | sed 's/,$//' )
    BATTERY_ICON=""
    BAT_COL="$FG"

    case $BATTERY_STATUS in
           'Charging') BATTERY_ICON="" ;;
           'Full') BATTERY_ICON="" ;;
    esac
    
    if [ $BATTERY_PERCENTAGE -lt 11 ] && [ $BATTERY_STATUS == 'Discharging' ]; then BAT_COL="$RED"; fi

    echo "%{F$BAT_COL}%{T4}$BATTERY_ICON%{T}%{F-} $BATTERY_PERCENTAGE%"
}

WiFi() {
    WIFI_SSID=$(iwgetid -r)
    WIFI_COL="$FG"
    if [ -z $WIFI_SSID ]; then WIFI_COL="$INACTIVE"; fi
    echo "%{F$WIFI_COL}%{T5}%{T}%{F-}"
}

Updates() {
    UP_COUNT=$(cat ~/.update_count | cut -d ";" -f 2)
    UP_ICON=""
    if [ ! $UP_COUNT == 0 ]; then echo "%{F$FG}%{T4}$UP_ICON%{T}%{F-}"; fi
}

CapsLock() {
    CAPS_SATUS=$(xset -q | grep 'Caps Lock:' | cut -d ' ' -f 10)
    if [ $CAPS_SATUS == 'on' ]; then echo "%{T5}%{T}"; fi
}

System(){
    SYSTEM_ICON=""
    echo "%{T5}$SYSTEM_ICON%{T}"
}

while true
do
    echo -e "%{l} $(System) \
             %{c}%{T5}%{T} $CURRENT_USER \
             %{r}$(CapsLock)  $(Updates)  $(WiFi)   $(Battery)      $(TimeDate)  "
    sleep .25
done | lemonbar -p -g 1343x23+12+12 -B $BG -F $FG -f $FONT_1 -f $FONT_2 -f $FONT_3 -f $FONT_4 -f $FONT_5 | sh
