#!/bin/bash

choice=$(echo -e "lock\nexit\nshutdown\nreboot\nscreenshot" | rofi -dmenu )

case $choice in 
    screenshot) sleep 1 && scrot & ;;
    lock) ;;
    exit) pkill -15 bar; bspc quit & ;;
    shutdown) systemctl poweroff & ;;
    reboot) systemctl reboot & ;;
esac

